# Generated by Django 2.1.7 on 2019-03-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190323_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
    ]
